### ISSUE TITLE
ERROR running force:source:deploy:  Deploy failed.

### ISSUE THREAD

**Issue by elk-gh** [trailheadapps/build-apps-with-lwc#4]
force-app\main\default\layouts\Contact-Contact Layout.layout-meta.xml  
In field: QuickAction - no QuickAction named FeedItem.RypplePost found

**Comment by tegeling** [comment]
Workaround: Remove lines 172 - 174 from Contact-Contact Layout.layout-meta.xml and redeploy

**Comment by muenzpraeger** [comment]
@pozil

**Comment by elk-gh** [comment]
Thank you. It solved the issue.

**Comment by pozil** [comment]
Fix deployed to master. Thanks for reporting this @elk-gh and thanks for the fix @tegeling.

**Comment by oagostinho** [comment]
Hi @pozil

I am getting now this error when I am deploying to a Dev Org:

sfdx force:source:deploy -p force-app -u lwc-recipes
Error  force-app/main/default/layouts/Account-Account Layout.layout-meta.xml  In field: QuickAction - no QuickAction named FeedItem.RypplePost found
ERROR running force:source:deploy:  Deploy failed. 

Any Idea?

**Comment by pozil** [comment]
Hi @oagostinho, thanks for reaching out. It would be better if you opened a new issue.

I'm a bit lost here because there is no account layout in this repository so I don't now where `Account-Account Layout.layout-meta.xml` is coming from.
Are you referring to the right repo or is this issue for [lwc-recipes](https://github.com/trailheadapps/lwc-recipes)?

**Comment by pozil** [comment]
Is that the issue: https://github.com/trailheadapps/lwc-recipes/issues/376

**Comment by oagostinho** [comment]
Hi

Yes, that one.
